---
workers: 1
logfile: default_connection.log

connections:
  - name: default
    host: localhost
    dbname: postgres
    user: postgres
    password: postgres
    port: 5432

tasks:
  - id: 1
    name: connect as dispatch by default
    type: psql
    command: \conninfo