# related to fljdin/dispatch#35
procs: 2
verbose: true
output: depends_on_loader_task.log

tasks:
  - id: 1
    name: "task #1 must load two others"
    loaded:
      from: sh
      command: |
        echo -n "sleep .2\nsleep .1\n"

  - id: 2
    name: "task #2 must wait for all subtask completion"
    from: sh
    command: "true"
    depends_on: [1]
