output: interrupted_task.log

tasks:
  - id: 1
    name: "task #1 must fail"
    command: false

  - id: 2
    name: "task #2 must be interrupted"
    command: true
    depends_on: [1]

  - id: 3
    name: "task #3 must be interrupted by cascade"
    command: true
    depends_on: [2]
