procs: 1
logfile: loaded_from_sql_file.log

environments:
  - name: default
    variables:
      PGHOST: localhost
      PGUSER: postgres

tasks:
  - id: 1
    name: dispatch queries from a sql file
    type: psql
    file: queries.sql
    variables: 
      PGHOST: localhost
      PGUSER: postgres
