procs: 1
logfile: loader_with_env.log

environments:
  - name: default
    variables:
      PGHOST: localhost
      PGUSER: postgres
  - name: bar
    variables:
      PGAPPNAME: bar

tasks:
  - id: 1
    name: Loader with environment variables
    type: sh
    variables:
      PGAPPNAME: foo
    loaded:
      from: psql
      env: bar
      command: |
        SELECT format('echo %s', current_setting('application_name'))
        UNION
        SELECT format('echo $PGAPPNAME')
