name: go-test-e2e

on: [push]

jobs:
  go-test:

    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: '1.21.x'

      - uses: mig4/setup-bats@v1.2.0
        with:
          bats-version: '1.9.0'
        
      - name: Build testing binary
        run: go build -tags testing

      - name: Test with bats
        run: bats t
