name: go-test-e2e

on: [push]

jobs:
  go-test:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20.x'

      - name: Test
        run: GOTEST=1 go test -v ./test