name: go-test-unit

on: [push]

jobs:
  go-test:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.x'

      - name: Test
        run: go test -v ./...
