name: nfpm-package

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20.x'

      - name: Install nfpm
        run: go install github.com/goreleaser/nfpm/v2/cmd/nfpm@latest
      
      - name: Build from sources
        run: go build
      
      - name: Package with nfpm
        run: >-
          mkdir -p packages ;
          for p in rpm deb ; do 
            nfpm package --packager $p --target packages ;
          done
      
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: packages
          path: packages