name: nfpm-package

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21.x'

      - name: Install nfpm
        run: go install github.com/goreleaser/nfpm/v2/cmd/nfpm@latest
      
      - name: Set version variable
        run: echo "APP_VERSION=$(grep 'version:' nfpm.yaml | awk '{print $2}')" >> $GITHUB_ENV

      - name: Build from sources
        run: go build -ldflags "-X main.version=${{ env.APP_VERSION }}"
        env:
          CGO_ENABLED: 0
      
      - name: Package with nfpm
        run: >-
          mkdir -p packages ;
          for p in rpm deb ; do 
            nfpm package --packager $p --target packages ;
          done
      
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: packages
          path: packages
