name: package-dispatch

on:
  workflow_dispatch:

jobs:
  build:
    name: Create RPM binary
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@main

      - name: build RPM package
        id: rpm_build
        uses: naveenrajm7/rpmbuild@master
        with:
          spec_file: "dispatch.spec"